CREATE DATABASE ferrorama;
USE ferrorama;

CREATE TABLE usuario(
id INT AUTO_INCREMENT PRIMARY KEY,
nome VARCHAR(100) NOT NULL,
email VARCHAR(100) NOT NULL UNIQUE,
senha VARCHAR(100) NOT NULL,
Telefone VARCHAR(15) NOT NULL

);

CREATE TABLE sensor(
id INT AUTO_INCREMENT PRIMARY KEY,
nome VARCHAR(100) NOT NULL,
localizacao VARCHAR(100) NOT NULL,
tipo VARCHAR(50) NOT NULL,
trem_alocado varchar(100) NOT NULL


);
